services:
  app:
    image: 405369522825.dkr.ecr.us-west-2.amazonaws.com/stac-fastapi-pgstac:6.0.0
    container_name: stac-fastapi-pgstac
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
      - ENABLE_TRANSACTIONS_EXTENSIONS=TRUE 
    ports:
      - "8082:8082"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
    command: bash -c "scripts/wait-for-it.sh ${PGHOST}:5432 && python -m stac_fastapi.pgstac.app"
    develop:
      watch:
        - action: rebuild
          path: ./stac_fastapi/pgstac

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app

networks:
  default:
    name: stac-fastapi-network
